version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: goszalupa_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - goszalupa_network

  redis:
    image: redis:7-alpine
    container_name: goszalupa_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - goszalupa_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goszalupa_app
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your-super-secret-jwt-key-here-change-in-production
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_EXPIRES_IN: 14d
      SESSION_SECRET: your-super-secret-session-key-here-change-in-production
    depends_on:
      - postgres
      - redis
    networks:
      - goszalupa_network

volumes:
  postgres_data:
  redis_data:

networks:
  goszalupa_network:
    driver: bridge
